[package]
name = "euchre-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
euchre-interface = { path = "../euchre-interface" }
euchre-engine = { path = "../euchre-engine" }
euchre-agents = { path = "../euchre-agents" }
clap = { version = "4.6.1", features = ["derive"] }

[[bin]]
name = "euchre-eval"
path = "src/main.rs"
